[default]

GRANIAN.SERVER.PORT = 8000
GRANIAN.SERVER.HOST = "0.0.0.0"
GRANIAN.SERVER.WORKERS = 1
GRANIAN.SERVER.RELOAD = false
GRANIAN.SERVER.FACTORY = true
GRANIAN.SERVER.TARGET_RUN = "app.core.app_factory:create_app"
GRANIAN.SERVER.LOG_LEVEL = 'info'
GRANIAN.SERVER.LOG_ACCESS = true


LOGGING.LEVEL = "INFO"
#LOGGING.FORMAT = "{message}"
LOGGING.FORMAT = "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level:<8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level> - <cyan>{extra}</cyan>" # или "text" для локальной разработки
LOGGING.PATH = "@none" #"logs/app.log"
LOGGING.ROTATION = "10 MB"
LOGGING.RETENTION = "10 days"
LOGGING.LOGGERS_TO_ROOT = [
    "uvicorn.asgi",
    "uvicorn.access",
    "fastapi",
    "granian",
    "_granian",
    "granian.access",
    "granian-worker",
]

METRICS.SERVICE_NAME = 'eva'
# Define custom buckets for request duration (in seconds)
# 5ms, 10ms, 25ms, 50ms, 75ms, 100ms, 250ms, 500ms, 750ms, 1s, 2.5s, 5s, 7.5s, 10s
METRICS.DURATION.BUCKETS = [
    0.005, 0.01, 0.025, 0.05, 0.075, 0.1,
    0.25, 0.5, 0.75, 1.0, 2.5, 5.0, 7.5, 10.0,
]

SECURITY.CORS.ORIGINS = ["*"]
SECURITY.CORS.ALLOW.CREDENTIALS = true
SECURITY.CORS.ALLOW.METHODS = ["*"]
SECURITY.CORS.ALLOW.HEADERS = ["*"]
SECURITY.TRUSTED.HOSTS = ["*"]

TRACING.OTLP.ENABLED = true
TRACING.OTLP.ENDPOINT = "console" #"http://localhost:4317" # "console" or "uri"
TRACING.OTLP.SERVICE_NAME = "eva"
TRACING.OTLP.INSECURE = false